#!/bin/sh
# vim: set ft=sh

set -e
set -o pipefail

exec 3>&1 # move stdout to 3 for returning our output
exec 1>&2 # redirect normal output to stderr for logging
source $(dirname $0)/common.sh

main(){
  request=$(mktemp /tmp/counter-request.XXXXXX)
  cat > $request <&0
  driver=$(jq -r '.source.driver // "s3"' < $request)
  includeDriver $driver
  number=$(pullCounter $request)
  jq -M -n "[{number: $(echo $number | jq -R .)}]" >&3
}

main
