#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # move stdout to 3 for returning our output
exec 1>&2 # redirect normal output to stderr for logging
source $(dirname $0)/common.sh

main(){
  source=$1
  request=$(mktemp /tmp/counter-request.XXXXXX)
  cat > $request <&0
  file=$(jq -r '.params.file // -1' < $request)
  driver=$(jq -r '.source.driver // "s3"' < $request)
  includeDriver $driver
  number=$(cat $source/$file)
  newNumber=$(process $request $number)
  $(pushCounter $request $newNumber)
  jq -M -n "{
    version: {
      number: $(echo $newNumber | jq -R .)
    },
    metadata: [
      {
         name:  $(echo "number" | jq -R .),
         value: $(echo $newNumber | jq -R .)
      }
    ]
  }" >&3
}

if [ -z "$1" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

main $1
